spring:
  main:
    web-application-type: servlet
  datasource:
    username: sa
    password: sa
    name: session-handling
    generate-unique-name: false
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none