INSERT INTO CUSTOMER VALUES(1,'Arthur Dent','A',10000);
INSERT INTO CUSTOMER VALUES(2,'Ford Prefect','B',5000);
INSERT INTO CUSTOMER VALUES(3,'Tricia Trillian McMillan','C',1000);
INSERT INTO CUSTOMER VALUES(4,'Zaphod Beeblebrox','D',500);
INSERT INTO CUSTOMER VALUES(5,'Marvin','A',100000);
INSERT INTO CUSTOMER VALUES(6,'Slartibartfast','D',100),