CREATE TABLE users (
  username VARCHAR(45) NOT NULL,
  password VARCHAR(60) NOT NULL,
  active TINYINT NOT NULL,
  PRIMARY KEY (username));

CREATE TABLE roles (
  role_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  username VARCHAR(45) NOT NULL,
  role VARCHAR(45) NOT NULL,
  PRIMARY KEY (role_id),
  CONSTRAINT fk_username FOREIGN KEY (username) REFERENCES users (username));

INSERT INTO users(username,password,active)
VALUES ('userA','$2a$10$uyw4NHXu52GKyc2iJRfyOu/p.jn2IXhibpvYEAO4AXcaTQ0LXBCnq', 1);

INSERT INTO users(username,password,active)
VALUES ('userB','$2a$10$VluCf12z6uXtoqham5FtFe1DZ4l20fONKECcFrNV2C5.raSeBRrfO', 1);

INSERT INTO roles (username, role)
VALUES ('userA', 'ROLE_USER');
INSERT INTO roles (username, role)
VALUES ('userB', 'ROLE_USER');

