CREATE TABLE contacts (
  id BIGINT NOT NULL AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL,
  firstname VARCHAR(50) NOT NULL,
  lastname VARCHAR(50) NOT NULL,
  comment VARCHAR(100) NOT NULL,
  PRIMARY KEY (id));
