name: Build

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: JavaSecurity Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Generate Codecov Report
        uses: codecov/codecov-action@v3