name: Build

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
          cache: 'maven'
      - name: Build with Maven
        run: mvn verify
      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          others: ''